# WorkInProgress Jobs
# ==============================================================================
#
# Pipeline executed when the developer is working in a work branch.

# Manual run only for WorkInProgress work branches (with no merge requests associated).
.only_for_wip_manual_rules: &only_for_wip_manual_rules
    rules:
        - if: '$CI_COMMIT_TAG == null && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "master" && $CI_OPEN_MERGE_REQUESTS == null'
          when: manual
        - when: never

# Opens a merge request from any work branch to trunk.
Create MR:
    extends: .create_merge_request
    stage: .post
    variables:
        ARG_TARGET_BRANCH: master
        ARG_MR_TEMPLATE: .gitlab/ci-cd/merge_request_templates/default.md
    <<: *only_for_wip_manual_rules
